-- Add AI summary caching to incoming_emails table
-- This reduces API costs and improves performance by caching AI-generated insights

ALTER TABLE incoming_emails
ADD COLUMN IF NOT EXISTS ai_summary JSONB DEFAULT NULL;

-- Add index for querying emails with AI summaries
CREATE INDEX IF NOT EXISTS idx_incoming_emails_ai_summary_generated
ON incoming_emails((ai_summary->>'generated_at'))
WHERE ai_summary IS NOT NULL;

-- Add comment for documentation
COMMENT ON COLUMN incoming_emails.ai_summary IS 'Cached AI-generated email insights including summary, intent, and contact status. Generated by Gemini AI.';
